# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\noroot\PycharmProjects\TFG\src\Viewer\ViewerWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ViewerWindow(object):
    def setupUi(self, ViewerWindow):
        ViewerWindow.setObjectName(_fromUtf8("ViewerWindow"))
        ViewerWindow.resize(589, 481)
        self.centralWidget = QtGui.QWidget(ViewerWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.statusFrame = QtGui.QFrame(self.centralWidget)
        self.statusFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.statusFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.statusFrame.setObjectName(_fromUtf8("statusFrame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.statusFrame)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(3)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.coordsLabel = QtGui.QLabel(self.statusFrame)
        self.coordsLabel.setFrameShape(QtGui.QFrame.Panel)
        self.coordsLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.coordsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.coordsLabel.setObjectName(_fromUtf8("coordsLabel"))
        self.gridLayout_2.addWidget(self.coordsLabel, 0, 0, 1, 1)
        self.valueLabel = QtGui.QLabel(self.statusFrame)
        self.valueLabel.setFrameShape(QtGui.QFrame.Panel)
        self.valueLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.valueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel.setObjectName(_fromUtf8("valueLabel"))
        self.gridLayout_2.addWidget(self.valueLabel, 0, 1, 1, 1)
        self.zoomLabel = QtGui.QLabel(self.statusFrame)
        self.zoomLabel.setFrameShape(QtGui.QFrame.Panel)
        self.zoomLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.zoomLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zoomLabel.setObjectName(_fromUtf8("zoomLabel"))
        self.gridLayout_2.addWidget(self.zoomLabel, 0, 2, 1, 1)
        self.elapsedTime = QtGui.QLabel(self.statusFrame)
        self.elapsedTime.setFrameShape(QtGui.QFrame.Panel)
        self.elapsedTime.setFrameShadow(QtGui.QFrame.Sunken)
        self.elapsedTime.setAlignment(QtCore.Qt.AlignCenter)
        self.elapsedTime.setIndent(-1)
        self.elapsedTime.setObjectName(_fromUtf8("elapsedTime"))
        self.gridLayout_2.addWidget(self.elapsedTime, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.statusFrame, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setAutoFillBackground(True)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.graphicsView = QtGui.QGraphicsView(self.tab)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.graphicsView.setPalette(palette)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.graphicsView.setFont(font)
        self.graphicsView.setAlignment(QtCore.Qt.AlignCenter)
        self.graphicsView.setRenderHints(QtGui.QPainter.TextAntialiasing)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout_3.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.previewTab = QtGui.QWidget()
        self.previewTab.setObjectName(_fromUtf8("previewTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.previewTab)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.preview = QtGui.QGraphicsView(self.previewTab)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.preview.setPalette(palette)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.preview.setFont(font)
        self.preview.setAlignment(QtCore.Qt.AlignCenter)
        self.preview.setRenderHints(QtGui.QPainter.TextAntialiasing)
        self.preview.setObjectName(_fromUtf8("preview"))
        self.gridLayout_4.addWidget(self.preview, 0, 0, 1, 1)
        self.tabWidget.addTab(self.previewTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        ViewerWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(ViewerWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 589, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout_us = QtGui.QMenu(self.menuBar)
        self.menuAbout_us.setObjectName(_fromUtf8("menuAbout_us"))
        self.menuInfo = QtGui.QMenu(self.menuBar)
        self.menuInfo.setObjectName(_fromUtf8("menuInfo"))
        ViewerWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(ViewerWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        ViewerWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionOpen_file = QtGui.QAction(ViewerWindow)
        self.actionOpen_file.setObjectName(_fromUtf8("actionOpen_file"))
        self.actionSave_Image = QtGui.QAction(ViewerWindow)
        self.actionSave_Image.setObjectName(_fromUtf8("actionSave_Image"))
        self.actionAbout_us = QtGui.QAction(ViewerWindow)
        self.actionAbout_us.setObjectName(_fromUtf8("actionAbout_us"))
        self.actionSplit_and_Merge = QtGui.QAction(ViewerWindow)
        self.actionSplit_and_Merge.setObjectName(_fromUtf8("actionSplit_and_Merge"))
        self.actionSave_polygon_layer = QtGui.QAction(ViewerWindow)
        self.actionSave_polygon_layer.setObjectName(_fromUtf8("actionSave_polygon_layer"))
        self.actionLoad_polygon_layer = QtGui.QAction(ViewerWindow)
        self.actionLoad_polygon_layer.setObjectName(_fromUtf8("actionLoad_polygon_layer"))
        self.actionLearnd_objects = QtGui.QAction(ViewerWindow)
        self.actionLearnd_objects.setObjectName(_fromUtf8("actionLearnd_objects"))
        self.actionHistogram = QtGui.QAction(ViewerWindow)
        self.actionHistogram.setObjectName(_fromUtf8("actionHistogram"))
        self.actionZoom100 = QtGui.QAction(ViewerWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Resources/Zoom100.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom100.setIcon(icon)
        self.actionZoom100.setObjectName(_fromUtf8("actionZoom100"))
        self.actionZoomFit = QtGui.QAction(ViewerWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Resources/ZoomFit.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomFit.setIcon(icon1)
        self.actionZoomFit.setObjectName(_fromUtf8("actionZoomFit"))
        self.actionPolygonalSelection = QtGui.QAction(ViewerWindow)
        self.actionPolygonalSelection.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Resources/polygon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPolygonalSelection.setIcon(icon2)
        self.actionPolygonalSelection.setObjectName(_fromUtf8("actionPolygonalSelection"))
        self.actionRectSelection = QtGui.QAction(ViewerWindow)
        self.actionRectSelection.setCheckable(True)
        self.actionRectSelection.setChecked(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Resources/rectangle.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRectSelection.setIcon(icon3)
        self.actionRectSelection.setObjectName(_fromUtf8("actionRectSelection"))
        self.actionPointSelection = QtGui.QAction(ViewerWindow)
        self.actionPointSelection.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Resources/points.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPointSelection.setIcon(icon4)
        self.actionPointSelection.setObjectName(_fromUtf8("actionPointSelection"))
        self.actionLockSelections = QtGui.QAction(ViewerWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/Resources/openLock.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLockSelections.setIcon(icon5)
        self.actionLockSelections.setObjectName(_fromUtf8("actionLockSelections"))
        self.actionLog = QtGui.QAction(ViewerWindow)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.actionSimilarity = QtGui.QAction(ViewerWindow)
        self.actionSimilarity.setObjectName(_fromUtf8("actionSimilarity"))
        self.actionBorders = QtGui.QAction(ViewerWindow)
        self.actionBorders.setObjectName(_fromUtf8("actionBorders"))
        self.actionCanny = QtGui.QAction(ViewerWindow)
        self.actionCanny.setObjectName(_fromUtf8("actionCanny"))
        self.actionGaussianBlur = QtGui.QAction(ViewerWindow)
        self.actionGaussianBlur.setObjectName(_fromUtf8("actionGaussianBlur"))
        self.actionLog_2 = QtGui.QAction(ViewerWindow)
        self.actionLog_2.setObjectName(_fromUtf8("actionLog_2"))
        self.actionExit = QtGui.QAction(ViewerWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionOpen_file)
        self.menuFile.addAction(self.actionSave_Image)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAbout_us.addAction(self.actionAbout_us)
        self.menuAbout_us.addAction(self.actionLog_2)
        self.menuInfo.addAction(self.actionHistogram)
        self.menuInfo.addAction(self.actionCanny)
        self.menuInfo.addAction(self.actionGaussianBlur)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuInfo.menuAction())
        self.menuBar.addAction(self.menuAbout_us.menuAction())
        self.mainToolBar.addAction(self.actionZoom100)
        self.mainToolBar.addAction(self.actionZoomFit)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionPolygonalSelection)
        self.mainToolBar.addAction(self.actionRectSelection)
        self.mainToolBar.addAction(self.actionPointSelection)
        self.mainToolBar.addAction(self.actionLockSelections)

        self.retranslateUi(ViewerWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ViewerWindow)

    def retranslateUi(self, ViewerWindow):
        ViewerWindow.setWindowTitle(_translate("ViewerWindow", "Vision Viewer", None))
        self.coordsLabel.setText(_translate("ViewerWindow", "Coords", None))
        self.valueLabel.setText(_translate("ViewerWindow", "Pixel value", None))
        self.zoomLabel.setText(_translate("ViewerWindow", "Zoom", None))
        self.elapsedTime.setText(_translate("ViewerWindow", "Elapsed time", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ViewerWindow", "Viewer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.previewTab), _translate("ViewerWindow", "Preview", None))
        self.menuFile.setTitle(_translate("ViewerWindow", "File", None))
        self.menuAbout_us.setTitle(_translate("ViewerWindow", "Help", None))
        self.menuInfo.setTitle(_translate("ViewerWindow", "Filters", None))
        self.actionOpen_file.setText(_translate("ViewerWindow", "Open image or video file", None))
        self.actionSave_Image.setText(_translate("ViewerWindow", "Save image file", None))
        self.actionAbout_us.setText(_translate("ViewerWindow", "About VisionViewer", None))
        self.actionSplit_and_Merge.setText(_translate("ViewerWindow", "Split and Merge", None))
        self.actionSave_polygon_layer.setText(_translate("ViewerWindow", "Save polygon layer", None))
        self.actionLoad_polygon_layer.setText(_translate("ViewerWindow", "Load polygon layer", None))
        self.actionLearnd_objects.setText(_translate("ViewerWindow", "Learnd objects", None))
        self.actionHistogram.setText(_translate("ViewerWindow", "Histogram", None))
        self.actionZoom100.setText(_translate("ViewerWindow", "zoom100", None))
        self.actionZoomFit.setText(_translate("ViewerWindow", "zoomFit", None))
        self.actionPolygonalSelection.setText(_translate("ViewerWindow", "polygonalSelection", None))
        self.actionRectSelection.setText(_translate("ViewerWindow", "rectSelection", None))
        self.actionPointSelection.setText(_translate("ViewerWindow", "pointSelection", None))
        self.actionLockSelections.setText(_translate("ViewerWindow", "lockSelections", None))
        self.actionLog.setText(_translate("ViewerWindow", "Log", None))
        self.actionSimilarity.setText(_translate("ViewerWindow", "Similarity", None))
        self.actionBorders.setText(_translate("ViewerWindow", "Borders", None))
        self.actionCanny.setText(_translate("ViewerWindow", "Canny", None))
        self.actionGaussianBlur.setText(_translate("ViewerWindow", "GaussianBlur", None))
        self.actionLog_2.setText(_translate("ViewerWindow", "Log", None))
        self.actionExit.setText(_translate("ViewerWindow", "Exit", None))
