__author__ = 'Rainer Arencibia Hernandez'

"""
    We use Builder so safe our filters, each one of this filters in saved in different packages by Name.
    For example: In the Histogram package we have a Window(Qt Designer - interface.ui) to show the information of the
    histograms, we have the code translated in python of the interface, generated by the pyuic4 program & we have
    the HistogramBuilder, which received a image and do the process of calculated the histograms, draw each
        histogram & connect the objects("checkbox") of the window to their respectively slots, by his signals.

    NOTE: Every developer will leave their code in a python package on this folder.
"""
