# -*- coding: utf-8 -*-
__author__ = 'Rainer Arencibia'

"""
The MIT License (MIT)

Copyright (c) 2016 Rainer Arencibia

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit
persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

""" We have here 4 python packages to organize and structure the project.
    1 - Builders
    2 - Operators
    3 - Viewer
    4 - Listeners

    1) We use Builder so safe our filters, each one of this filters in saved in different packages by Name.
    For example: In the Histogram package we have a Window(Qt Designer - interface.ui) to show the information of the
    histograms, we have the code translated in python of the interface, generated by the pyuic4 program & we have
    the HistogramBuilder, which received a image and do the process of calculated the histograms, draw each
        histogram & connect the objects("checkbox") of the window to their respectively slots, by his signals.

    NOTE: Every developer will leave their code in a python package on this folder.

    2) On the Operators package we have 3 categories to organize each filter on the project.
        1 - Builder
        2 - Configurator
        3 - Descriptor

    Category Configurator: "mandatory parameters"
    Some filters will need special setting to work (ie: "Canny Filter:" sigma, X, Y, threshold, etc).

    Category Builder: "optional parameters" -- "Do not confuse with the Builders packages for filters".
    Other filter will need optional setting to work, this it´s the case of the Gaussian Blur filter.
    This category it´s for filter that may need this parameters. But their are not needed by default.

    Category Descriptor: "With out parameters"
    This type of filter, do not need any extra parameters, just take a image or a frame and take
    what he need from the image it self. For example: Histogram filter.

    3) In Viewer you will find the main "VisionViewer.py" and the interfaces of generals applications like
    About us, the principal window of the program. A navigator window to surf on the history of a process file.
    And of course the python code translated by the pyuic4 program of each interface. All the interface are created
    with the Qt Designer in using functions of the PyQt4 library.

    Also we have here a package named "Resources" to safe icon, images or any other information useful.

    4) On the Listeners package you will see two class:
        1 - OperatorListener
        2 - ImageListener
    As the name said if you choose a different filter or a image the main program will know & will
    tell you if the filter can apply to the image selected. (Filter compatible with an image => Filter On)
"""

